[[Libglvnd]]
arch = "aarch64"
git-tree-sha1 = "c3af4fa0c11a7fa7efd04888f1b14bccf6c1b1e0"
libc = "musl"
os = "linux"

    [[Libglvnd.download]]
    sha256 = "046bc3cc6bc9cecd34d554f3d534a15100448a18b6000c2efbcc462c0382a8e7"
    url = "https://github.com/JuliaBinaryWrappers/Libglvnd_jll.jl/releases/download/Libglvnd-v1.3.0+1/Libglvnd.v1.3.0.aarch64-linux-musl.tar.gz"
[[Libglvnd]]
arch = "aarch64"
git-tree-sha1 = "4dc50e1b05a20c4acf89bed21501c4181138423e"
libc = "glibc"
os = "linux"

    [[Libglvnd.download]]
    sha256 = "60b1a6b521400c684e4d06858567e599137bc97b2c16a6ef6689d5647b7a791d"
    url = "https://github.com/JuliaBinaryWrappers/Libglvnd_jll.jl/releases/download/Libglvnd-v1.3.0+1/Libglvnd.v1.3.0.aarch64-linux-gnu.tar.gz"
[[Libglvnd]]
arch = "x86_64"
git-tree-sha1 = "3972ca006494ebc42af5d795a626fc324f15e313"
libc = "glibc"
os = "linux"

    [[Libglvnd.download]]
    sha256 = "46f3e17a0dc1288441c97ca29bdafa186e97c204751b303dea4937e85e56dd5f"
    url = "https://github.com/JuliaBinaryWrappers/Libglvnd_jll.jl/releases/download/Libglvnd-v1.3.0+1/Libglvnd.v1.3.0.x86_64-linux-gnu.tar.gz"
[[Libglvnd]]
arch = "powerpc64le"
git-tree-sha1 = "34a21f9ff6966639bb481afe8d83bc3d1f5f304d"
libc = "glibc"
os = "linux"

    [[Libglvnd.download]]
    sha256 = "d009e1e0406cfbc47cf7ba584e5d79a9ec84e157e502c80866c18a0fff6a1c32"
    url = "https://github.com/JuliaBinaryWrappers/Libglvnd_jll.jl/releases/download/Libglvnd-v1.3.0+1/Libglvnd.v1.3.0.powerpc64le-linux-gnu.tar.gz"
[[Libglvnd]]
arch = "x86_64"
git-tree-sha1 = "becf8d0c47ee66df3615576b78d6a9a92df460ed"
os = "freebsd"

    [[Libglvnd.download]]
    sha256 = "a7da00d6af00f0149d869c8f72b12f0eec059400fbe6a49f7b8c9e96663cbf43"
    url = "https://github.com/JuliaBinaryWrappers/Libglvnd_jll.jl/releases/download/Libglvnd-v1.3.0+1/Libglvnd.v1.3.0.x86_64-unknown-freebsd11.1.tar.gz"
[[Libglvnd]]
arch = "i686"
git-tree-sha1 = "19cea06f6a70bc12e4f95d8dac7195bb3e713d62"
libc = "glibc"
os = "linux"

    [[Libglvnd.download]]
    sha256 = "3496b6beae4bf50b68907c749002326f5743da41587a146e683a81b51947a655"
    url = "https://github.com/JuliaBinaryWrappers/Libglvnd_jll.jl/releases/download/Libglvnd-v1.3.0+1/Libglvnd.v1.3.0.i686-linux-gnu.tar.gz"
[[Libglvnd]]
arch = "i686"
git-tree-sha1 = "150f773ed5882193432ca3a554601986ebc4d61e"
libc = "musl"
os = "linux"

    [[Libglvnd.download]]
    sha256 = "dfa18c842f5edff62a01e00e46bdebe061220274a9443745a32428f01b16f62d"
    url = "https://github.com/JuliaBinaryWrappers/Libglvnd_jll.jl/releases/download/Libglvnd-v1.3.0+1/Libglvnd.v1.3.0.i686-linux-musl.tar.gz"
[[Libglvnd]]
arch = "armv7l"
git-tree-sha1 = "0cb6fa9b65897ecbe04bba2e8effe511d3ca1bfc"
libc = "glibc"
os = "linux"

    [[Libglvnd.download]]
    sha256 = "383bba9bf9fd26513f7fd3aba6f3676a6dc98dcb444c84d657e0cf0b60245c11"
    url = "https://github.com/JuliaBinaryWrappers/Libglvnd_jll.jl/releases/download/Libglvnd-v1.3.0+1/Libglvnd.v1.3.0.armv7l-linux-gnueabihf.tar.gz"
[[Libglvnd]]
arch = "x86_64"
git-tree-sha1 = "6ffe94a97b8fde49babd75ba7331d5440b3c1a7a"
libc = "musl"
os = "linux"

    [[Libglvnd.download]]
    sha256 = "2ed1118ec5c109af5a1c4309a05bfb63d4e859949ea3d0271c8c43bbfa8ff60d"
    url = "https://github.com/JuliaBinaryWrappers/Libglvnd_jll.jl/releases/download/Libglvnd-v1.3.0+1/Libglvnd.v1.3.0.x86_64-linux-musl.tar.gz"
[[Libglvnd]]
arch = "armv7l"
git-tree-sha1 = "24acec375902aaa3f7fe907fb284f004ab7922f7"
libc = "musl"
os = "linux"

    [[Libglvnd.download]]
    sha256 = "a1c805b60d2c5efb232cfbb2595ca43f346cc3cd52b167caf25b9dea9be3b1be"
    url = "https://github.com/JuliaBinaryWrappers/Libglvnd_jll.jl/releases/download/Libglvnd-v1.3.0+1/Libglvnd.v1.3.0.armv7l-linux-musleabihf.tar.gz"
