[[Libglvnd]]
arch = "aarch64"
git-tree-sha1 = "fd215510a44340fb54e7ff746ab9e5da3172ebbc"
libc = "musl"
os = "linux"

    [[Libglvnd.download]]
    sha256 = "a6258a87e19b1c29b9e68b329e99bef0bbf9278d135688c6ae674667db1bb902"
    url = "https://github.com/JuliaBinaryWrappers/Libglvnd_jll.jl/releases/download/Libglvnd-v1.3.0+0/Libglvnd.v1.3.0.aarch64-linux-musl.tar.gz"
[[Libglvnd]]
arch = "aarch64"
git-tree-sha1 = "557c44be922f5c64f1f1a52c6bb27b78ea574641"
libc = "glibc"
os = "linux"

    [[Libglvnd.download]]
    sha256 = "208e20bd16e07a60b9bacbc5f9f80e3328194791e5f11ebb50e700b7f918f662"
    url = "https://github.com/JuliaBinaryWrappers/Libglvnd_jll.jl/releases/download/Libglvnd-v1.3.0+0/Libglvnd.v1.3.0.aarch64-linux-gnu.tar.gz"
[[Libglvnd]]
arch = "x86_64"
git-tree-sha1 = "72dc51c7c134cde8e07bd051165792c3fed88bf2"
libc = "glibc"
os = "linux"

    [[Libglvnd.download]]
    sha256 = "c95e0e24efb36af5289651e8c3d6c111d090fd71181ccc13a6e79ea68123c202"
    url = "https://github.com/JuliaBinaryWrappers/Libglvnd_jll.jl/releases/download/Libglvnd-v1.3.0+0/Libglvnd.v1.3.0.x86_64-linux-gnu.tar.gz"
[[Libglvnd]]
arch = "powerpc64le"
git-tree-sha1 = "eae526367955076fb4ea485a248f981ebf3d9c58"
libc = "glibc"
os = "linux"

    [[Libglvnd.download]]
    sha256 = "557d3bd4d5b2d3524df1c1aee1f11c27e45a13141f1ae3e938129bfe64a10c59"
    url = "https://github.com/JuliaBinaryWrappers/Libglvnd_jll.jl/releases/download/Libglvnd-v1.3.0+0/Libglvnd.v1.3.0.powerpc64le-linux-gnu.tar.gz"
[[Libglvnd]]
arch = "x86_64"
git-tree-sha1 = "34096f9939c9dcd5cc25f7b2b0ec5bcd5a7f0b92"
os = "freebsd"

    [[Libglvnd.download]]
    sha256 = "2381a1d09e37a04f75a1158d51a0946bead6d1993ce896358c9418efc530ebf4"
    url = "https://github.com/JuliaBinaryWrappers/Libglvnd_jll.jl/releases/download/Libglvnd-v1.3.0+0/Libglvnd.v1.3.0.x86_64-unknown-freebsd11.1.tar.gz"
[[Libglvnd]]
arch = "i686"
git-tree-sha1 = "c6e60004f7ea3bdcd6aa0d23c058ff3d0da4d2eb"
libc = "glibc"
os = "linux"

    [[Libglvnd.download]]
    sha256 = "9970f9fc0535b75c7cf95994701943e905eeaf9e5711aae0933a2da26b9fa015"
    url = "https://github.com/JuliaBinaryWrappers/Libglvnd_jll.jl/releases/download/Libglvnd-v1.3.0+0/Libglvnd.v1.3.0.i686-linux-gnu.tar.gz"
[[Libglvnd]]
arch = "i686"
git-tree-sha1 = "61294368fc030b09a42edea7136de04a7298d80c"
libc = "musl"
os = "linux"

    [[Libglvnd.download]]
    sha256 = "e1428d41566e314fd72f562f8c1b7ab80afbe778b8ec642c9f9a939e973c602f"
    url = "https://github.com/JuliaBinaryWrappers/Libglvnd_jll.jl/releases/download/Libglvnd-v1.3.0+0/Libglvnd.v1.3.0.i686-linux-musl.tar.gz"
[[Libglvnd]]
arch = "armv7l"
git-tree-sha1 = "587b1ad37d9fdb5c73f40099a6b506486f9712de"
libc = "glibc"
os = "linux"

    [[Libglvnd.download]]
    sha256 = "711bfa549c435511e182e822ba045da23d4a95af7ac378e12fbb341f20949931"
    url = "https://github.com/JuliaBinaryWrappers/Libglvnd_jll.jl/releases/download/Libglvnd-v1.3.0+0/Libglvnd.v1.3.0.armv7l-linux-gnueabihf.tar.gz"
[[Libglvnd]]
arch = "x86_64"
git-tree-sha1 = "4aa56ffe34e3123e323dde25ee1481a5ac7c0eb2"
libc = "musl"
os = "linux"

    [[Libglvnd.download]]
    sha256 = "136ded3cff6e729ab4a73567880b4e11c11668c846cda46a439ce6a2d7696f2a"
    url = "https://github.com/JuliaBinaryWrappers/Libglvnd_jll.jl/releases/download/Libglvnd-v1.3.0+0/Libglvnd.v1.3.0.x86_64-linux-musl.tar.gz"
[[Libglvnd]]
arch = "armv7l"
git-tree-sha1 = "9f301c71a9350b869e456ee8ad601421eeb30112"
libc = "musl"
os = "linux"

    [[Libglvnd.download]]
    sha256 = "52f3d05a5f496ba9d1fe25be1235bce86b5dbaff9885383fdcab0251cbe87572"
    url = "https://github.com/JuliaBinaryWrappers/Libglvnd_jll.jl/releases/download/Libglvnd-v1.3.0+0/Libglvnd.v1.3.0.armv7l-linux-musleabihf.tar.gz"
