[[Libglvnd]]
arch = "x86_64"
git-tree-sha1 = "317a18856ac1365afd7934f54150ae61e08b0450"
os = "freebsd"

    [[Libglvnd.download]]
    sha256 = "bb74bb98b8f064c9de0002f71f995377d6281e8149206bb791435694d30c31c2"
    url = "https://github.com/JuliaBinaryWrappers/Libglvnd_jll.jl/releases/download/Libglvnd-v1.2.0+2/Libglvnd.v1.2.0.x86_64-unknown-freebsd11.1.tar.gz"
[[Libglvnd]]
arch = "i686"
git-tree-sha1 = "7864d2f380bb3678950fd74e690e27c0a138a79b"
libc = "glibc"
os = "linux"

    [[Libglvnd.download]]
    sha256 = "78cd8de39f36040c2a346028d628bae3eaaed8d0b9511d4c49c7f36f46bb7d00"
    url = "https://github.com/JuliaBinaryWrappers/Libglvnd_jll.jl/releases/download/Libglvnd-v1.2.0+2/Libglvnd.v1.2.0.i686-linux-gnu.tar.gz"
[[Libglvnd]]
arch = "armv7l"
git-tree-sha1 = "74ca332afdd8c5c86d3bda29c30b7a174535c231"
libc = "glibc"
os = "linux"

    [[Libglvnd.download]]
    sha256 = "b00f727f3b43f99ce47c3e6dbd99fed4c8008087ad0eb293dd4216875f2128ef"
    url = "https://github.com/JuliaBinaryWrappers/Libglvnd_jll.jl/releases/download/Libglvnd-v1.2.0+2/Libglvnd.v1.2.0.arm-linux-gnueabihf.tar.gz"
[[Libglvnd]]
arch = "armv7l"
git-tree-sha1 = "fb8e4c10b40dadd2d4c8ba276dad22f979f2bf64"
libc = "musl"
os = "linux"

    [[Libglvnd.download]]
    sha256 = "397e8dba9b86c96ee4e6f5285e8a15bf2b64ce1be63db1684f658a4c8d9a8052"
    url = "https://github.com/JuliaBinaryWrappers/Libglvnd_jll.jl/releases/download/Libglvnd-v1.2.0+2/Libglvnd.v1.2.0.arm-linux-musleabihf.tar.gz"
[[Libglvnd]]
arch = "i686"
git-tree-sha1 = "1880aee373d86776ea2059bdd2f251f58c254f6d"
libc = "musl"
os = "linux"

    [[Libglvnd.download]]
    sha256 = "eabc1d01a428642531c473b97ace31549f6aff60c17b3fc1cfba7ce8cbd2b7c8"
    url = "https://github.com/JuliaBinaryWrappers/Libglvnd_jll.jl/releases/download/Libglvnd-v1.2.0+2/Libglvnd.v1.2.0.i686-linux-musl.tar.gz"
[[Libglvnd]]
arch = "x86_64"
git-tree-sha1 = "958f14ac09ce5cc2f5f6ec439a48b868513d6c5c"
libc = "glibc"
os = "linux"

    [[Libglvnd.download]]
    sha256 = "9faf74fc3959582f9a56839e760de4e80e90a3bd79b6dd6432a65e09edd32557"
    url = "https://github.com/JuliaBinaryWrappers/Libglvnd_jll.jl/releases/download/Libglvnd-v1.2.0+2/Libglvnd.v1.2.0.x86_64-linux-gnu.tar.gz"
[[Libglvnd]]
arch = "aarch64"
git-tree-sha1 = "f3ad9464571859983cf8bd2471037397a6ce4853"
libc = "glibc"
os = "linux"

    [[Libglvnd.download]]
    sha256 = "e3510e5dbb368b85302930883df4adfea2381621f542ea4b614f75e3f8c78c45"
    url = "https://github.com/JuliaBinaryWrappers/Libglvnd_jll.jl/releases/download/Libglvnd-v1.2.0+2/Libglvnd.v1.2.0.aarch64-linux-gnu.tar.gz"
[[Libglvnd]]
arch = "powerpc64le"
git-tree-sha1 = "d0827bf55a6b32c5cf2168290200b1f8ba6156c1"
libc = "glibc"
os = "linux"

    [[Libglvnd.download]]
    sha256 = "4eb701bb2c5815a9e0da132f0b0d89527eca057e95be1c9b503e8940c8229d82"
    url = "https://github.com/JuliaBinaryWrappers/Libglvnd_jll.jl/releases/download/Libglvnd-v1.2.0+2/Libglvnd.v1.2.0.powerpc64le-linux-gnu.tar.gz"
[[Libglvnd]]
arch = "x86_64"
git-tree-sha1 = "791ab916ba041b4e45370ba06e7138f3ac2e84a3"
libc = "musl"
os = "linux"

    [[Libglvnd.download]]
    sha256 = "72e747f99ddc20ea0b48e79f3316f5fc37af42c5ab51407b49eacb4055e18dea"
    url = "https://github.com/JuliaBinaryWrappers/Libglvnd_jll.jl/releases/download/Libglvnd-v1.2.0+2/Libglvnd.v1.2.0.x86_64-linux-musl.tar.gz"
[[Libglvnd]]
arch = "aarch64"
git-tree-sha1 = "514bbbf366dccaf80de8e872139d29cdfcd95647"
libc = "musl"
os = "linux"

    [[Libglvnd.download]]
    sha256 = "90020f431e868c331708e0cf558621699bd6246700742ef943598e7cba10503a"
    url = "https://github.com/JuliaBinaryWrappers/Libglvnd_jll.jl/releases/download/Libglvnd-v1.2.0+2/Libglvnd.v1.2.0.aarch64-linux-musl.tar.gz"
